spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
          filters:
            - AuthenticationFilter
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**
          filters:
            - AuthenticationFilter
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
# Eureka Discovery Server Config
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9090

SECRET: 612c7ded6c80b46e1d2e6c601a93d5a9d944a5b4754d74feb664533e387a638f