spring:
  application:
    name: auth-service
  # DB Config
  data:
    mongodb:
      uri: mongodb://localhost:27017/AuthService
      auto-index-creation: true
  # Admin Server Config
  boot:
    admin:
      client:
        url: http://localhost:1111/
# Eureka Discovery Server Config
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8085
# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: '*'

SECRET: 612c7ded6c80b46e1d2e6c601a93d5a9d944a5b4754d74feb664533e387a638f

API-KEY: 3f5412e1e987d1808b7196426acb19ce594b847a21eb2a9d4e008a92885a46f7