spring:
  application:
    name: booking-service
  # DB Config
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BookingService
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # Admin Server Config
  boot:
    admin:
      client:
        url: http://localhost:1111/
# Eureka Discovery Server Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: '*'