spring:
  application:
    name: customer-service
  # DB Config
  data:
    mongodb:
      uri: mongodb://localhost:27017/CustomerService
      auto-index-creation: true
  # Admin Server Config
  boot:
    admin:
      client:
        url: http://localhost:1111/
# Eureka Discovery Server Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: '*'

API-KEY: 3f5412e1e987d1808b7196426acb19ce594b847a21eb2a9d4e008a92885a46f7