spring:
  application:
    name: customer-service
  # DB Config
  data:
    mongodb:
      uri: mongodb://localhost:27017/CustomerService
  # Admin Server Config
  boot:
    admin:
      client:
        url: http://localhost:1111/
# Eureka Discovery Server Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: '*'