spring:
  application:
    name: room-service
  # DB Config
  data:
    mongodb:
      uri: mongodb://localhost:27017/RoomService
  # Admin Server Config
  boot:
    admin:
      client:
        url: http://localhost:1111/
# Eureka Discovery Server Config
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8081
# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: '*'